### ISSUE TITLE
docker-image is no longer working

### ISSUE THREAD

**Issue by candysmurf** [Hawkular-QE/hawkular-services-docker#6]
the docker image worked fine for Hawkular. It's no longer working. For example:

command:
```
curl -u jdoe:password -X GET http://192.168.99.100:8080/hawkular/metrics/metrics -H "Content-Type: application/json" -H "Hawkular-Tenant: myTenant"
```

Response:
```
{"errorMsg":"WELD-000052: Cannot return null from a non-dependent producer method: Producer for Producer Method [MetricsService] with qualifiers [@Any @Default] declared as [[BackedAnnotatedMethod] @Produces @ApplicationScoped public org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle.getMetricsService()] declared on Managed Bean [class org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle] with qualifiers [@Any @Default]\n\tat org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle.getMetricsService(MetricsServiceLifecycle.java:0)\n  StackTrace:"}%
```

If going into Cassandra, you can see the table is empty:
```
 cqlsh:hawkular_metrics> select * from data;

 tenant_id | type | metric | dpart | time | availability | l_value | n_value | s_value | tags
-----------+------+--------+-------+------+--------------+---------+---------+---------+------

(0 rows)

```

Before this table was self-populating. We have a product depending on this. Please help. thanks.

**Comment by stefannegrea** [comment]
@candysmurf, what version of Metrics are you running or trying to run? Do you currently use just Metrics or the entire Hawkular Services?

**Comment by candysmurf** [comment]
@stefannegrea, I'm using [hawkular-client-go](https://github.com/hawkular/hawkular-client-go) running this docker images for integration testing. Mainly I use metrics. Thanks

**Comment by candysmurf** [comment]
it worked before the last commit which is HAWKULAR_VERSION=0.24.0.Final-SNAPSHOT.  I'm not able to build a docker images for that version. The error is:

```
Step 4 : ADD build-env runtime-env output/hawkular-services-dist.zip hawkular-install.sh check-cnode.sh hawkular-start.sh ${JBOSS_BASE}/
lstat output/hawkular-services-dist.zip: no such file or directory

```

Do you mind to push an image for that older version?

**Comment by vnugent** [comment]
@candysmurf the QE team created this image to to do integration test with OpenShift.  It's unfortunate that the recent upgrade broke your code.  I want to bring to your attention the `hawkular/hawkular-services` image maintained by the development team.  Would you be able to switch?  We're doing some additional testing and will soon make the switch ourselves. I have verified the following works:
```
# Start Cassandra 
# docker run --name hawkular-cassandra -e CASSANDRA_START_RPC=true -d cassandra:3.0.9

# Start Hawkular. Notice the new ADMIN_TOKEN env
# docker run --link=hawkular-cassandra -v /var/hawkular:/opt/data -e CASSANDRA_NODES=hawkular-cassandra -p 8080:8080 -e ADMIN_TOKEN=topsecret hawkular/hawkular-services:latest

# curl -u jdoe:password  http://192.168.0.9:8080/hawkular/metrics/metrics -H "Content-Type: application/json" -H "Hawkular-Admin-Token:topsecret" -H "Hawkular-Tenant:admin"
``` 

Could you elaborate a bit more on your use case?   Stefan (who responded earlier) is in the development team and may be able to help you more.

**Comment by candysmurf** [comment]
@vnugent, I'm not able to run your command. May I know why Cassandra has to be 3.0.9?

```
docker run --link=hawkular-cassandra -v /var/hawkular:/opt/data -e CASSANDRA_NODES=hawkular-cassandra -p 8080:8080 -e ADMIN_TOKEN=topsecret hawkular/hawkular-services:latest
Unable to find image 'hawkular/hawkular-services:latest' locally
latest: Pulling from hawkular/hawkular-services
45a2e645736c: Pull complete
f11bec86d3fc: Pull complete
6275a4ad0275: Pull complete
9905334bc95a: Pull complete
846e9c07b61d: Pull complete
aa820b779342: Pull complete
4fe1d9bdb6ce: Pull complete
Digest: sha256:f82ff9dc7c4c7c70dc13db3490f1646af1dcdb07515e3a50663b0dc2331f716a
Status: Downloaded newer image for hawkular/hawkular-services:latest
Added user 'jdoe' to file '/opt/jboss/wildfly/standalone/configuration/application-users.properties'
Added user 'jdoe' to file '/opt/jboss/wildfly/domain/configuration/application-users.properties'
Added user 'jdoe' with groups read-write,read-only to file '/opt/jboss/wildfly/standalone/configuration/application-roles.properties'
Added user 'jdoe' with groups read-write,read-only to file '/opt/jboss/wildfly/domain/configuration/application-roles.properties'
=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /opt/jboss/wildfly

  JAVA: /usr/lib/jvm/java/bin/java

  JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -Dhawkular.agent.machine.id=c2cafd631218 -Djboss.server.name=c2cafd631218 -Dhawkular.agent.in-container=true -Dhawkular.rest.feedId=c2cafd631218 -Dhawkular.agent.immutable=true

=========================================================================

java.lang.IllegalArgumentException: Failed to instantiate class "org.jboss.logmanager.handlers.PeriodicRotatingFileHandler" for handler "FILE"
	at org.jboss.logmanager.config.AbstractPropertyConfiguration$ConstructAction.validate(AbstractPropertyConfiguration.java:116)
	at org.jboss.logmanager.config.LogContextConfigurationImpl.doPrepare(LogContextConfigurationImpl.java:335)
	at org.jboss.logmanager.config.LogContextConfigurationImpl.prepare(LogContextConfigurationImpl.java:288)
	at org.jboss.logmanager.config.LogContextConfigurationImpl.commit(LogContextConfigurationImpl.java:297)
	at org.jboss.logmanager.PropertyConfigurator.configure(PropertyConfigurator.java:546)
	at org.jboss.logmanager.PropertyConfigurator.configure(PropertyConfigurator.java:97)
	at org.jboss.logmanager.LogManager.readConfiguration(LogManager.java:514)
	at org.jboss.logmanager.LogManager.readConfiguration(LogManager.java:476)
	at java.util.logging.LogManager$3.run(LogManager.java:399)
	at java.util.logging.LogManager$3.run(LogManager.java:396)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:396)
	at java.util.logging.LogManager.access$800(LogManager.java:145)
	at java.util.logging.LogManager$2.run(LogManager.java:345)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
	at java.util.logging.LogManager.getLogManager(LogManager.java:378)
	at org.jboss.modules.Main.main(Main.java:480)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jboss.logmanager.config.AbstractPropertyConfiguration$ConstructAction.validate(AbstractPropertyConfiguration.java:114)
	... 17 more
Caused by: java.io.FileNotFoundException: /opt/data/log/server.log (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.jboss.logmanager.handlers.FileHandler.setFile(FileHandler.java:151)
	at org.jboss.logmanager.handlers.PeriodicRotatingFileHandler.setFile(PeriodicRotatingFileHandler.java:108)
	at org.jboss.logmanager.handlers.FileHandler.setFileName(FileHandler.java:189)
	at org.jboss.logmanager.handlers.FileHandler.<init>(FileHandler.java:119)
	at org.jboss.logmanager.handlers.PeriodicRotatingFileHandler.<init>(PeriodicRotatingFileHandler.java:76)
	... 22 more
java.lang.IllegalStateException: WFLYSRV0124: Could not create server data directory: /opt/data/data
	at org.jboss.as.server.ServerEnvironment.<init>(ServerEnvironment.java:473)
	at org.jboss.as.server.Main.determineEnvironment(Main.java:297)
	at org.jboss.as.server.Main.main(Main.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.modules.Module.run(Module.java:330)
	at org.jboss.modules.Main.main(Main.java:505)

```

**Comment by vnugent** [comment]
You can create the data subdirectoy  `mkdir -p /var/hawkular/data` and retry?

**Comment by stefannegrea** [comment]
@candysmurf, the versions of [Hawkular Metrics](https://github.com/hawkular/hawkular-metrics) and [Hawkular Alerting](https://github.com/hawkular/hawkular-alerts) bundled in that deployment have been tested and certified to work with Cassandra 3.0.9. The 3.0.x line is more stable and has all the features needed to run both projects. Please keep an eye on the [Hawkular Metrics project](https://github.com/hawkular/hawkular-metrics) and [release announcement ](https://github.com/hawkular/hawkular-metrics/releases)regarding Cassandra compatibility changes.

**Comment by candysmurf** [comment]
@vnugent, I created the directory "/var/hawkular/data", but I still got a bunch of errors. The purpose of Docker image is not to have to create a lot local stuff manually. Why do we have to do this now? Please enlighten me. Thanks for your help!

```
▶ docker run --link=hawkular-cassandra -v /var/hawkular:/opt/data -e CASSANDRA_NODES=hawkular-cassandra -p 8080:8080 -e ADMIN_TOKEN=topsecret hawkular/hawkular-services:latest
Unable to find image 'hawkular/hawkular-services:latest' locally
latest: Pulling from hawkular/hawkular-services
45a2e645736c: Pull complete
f11bec86d3fc: Pull complete
6275a4ad0275: Pull complete
9905334bc95a: Pull complete
846e9c07b61d: Pull complete
aa820b779342: Pull complete
4fe1d9bdb6ce: Pull complete
Digest: sha256:f82ff9dc7c4c7c70dc13db3490f1646af1dcdb07515e3a50663b0dc2331f716a
Status: Downloaded newer image for hawkular/hawkular-services:latest
Added user 'jdoe' to file '/opt/jboss/wildfly/standalone/configuration/application-users.properties'
Added user 'jdoe' to file '/opt/jboss/wildfly/domain/configuration/application-users.properties'
Added user 'jdoe' with groups read-write,read-only to file '/opt/jboss/wildfly/standalone/configuration/application-roles.properties'
Added user 'jdoe' with groups read-write,read-only to file '/opt/jboss/wildfly/domain/configuration/application-roles.properties'
=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /opt/jboss/wildfly

  JAVA: /usr/lib/jvm/java/bin/java

  JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -Dhawkular.agent.machine.id=69e19f12d376 -Djboss.server.name=69e19f12d376 -Dhawkular.agent.in-container=true -Dhawkular.rest.feedId=69e19f12d376 -Dhawkular.agent.immutable=true

=========================================================================

java.lang.IllegalArgumentException: Failed to instantiate class "org.jboss.logmanager.handlers.PeriodicRotatingFileHandler" for handler "FILE"
	at org.jboss.logmanager.config.AbstractPropertyConfiguration$ConstructAction.validate(AbstractPropertyConfiguration.java:116)
	at org.jboss.logmanager.config.LogContextConfigurationImpl.doPrepare(LogContextConfigurationImpl.java:335)
	at org.jboss.logmanager.config.LogContextConfigurationImpl.prepare(LogContextConfigurationImpl.java:288)
	at org.jboss.logmanager.config.LogContextConfigurationImpl.commit(LogContextConfigurationImpl.java:297)
	at org.jboss.logmanager.PropertyConfigurator.configure(PropertyConfigurator.java:546)
	at org.jboss.logmanager.PropertyConfigurator.configure(PropertyConfigurator.java:97)
	at org.jboss.logmanager.LogManager.readConfiguration(LogManager.java:514)
	at org.jboss.logmanager.LogManager.readConfiguration(LogManager.java:476)
	at java.util.logging.LogManager$3.run(LogManager.java:399)
	at java.util.logging.LogManager$3.run(LogManager.java:396)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:396)
	at java.util.logging.LogManager.access$800(LogManager.java:145)
	at java.util.logging.LogManager$2.run(LogManager.java:345)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
	at java.util.logging.LogManager.getLogManager(LogManager.java:378)
	at org.jboss.modules.Main.main(Main.java:480)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jboss.logmanager.config.AbstractPropertyConfiguration$ConstructAction.validate(AbstractPropertyConfiguration.java:114)
	... 17 more
Caused by: java.io.FileNotFoundException: /opt/data/log/server.log (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.jboss.logmanager.handlers.FileHandler.setFile(FileHandler.java:151)
	at org.jboss.logmanager.handlers.PeriodicRotatingFileHandler.setFile(PeriodicRotatingFileHandler.java:108)
	at org.jboss.logmanager.handlers.FileHandler.setFileName(FileHandler.java:189)
	at org.jboss.logmanager.handlers.FileHandler.<init>(FileHandler.java:119)
	at org.jboss.logmanager.handlers.PeriodicRotatingFileHandler.<init>(PeriodicRotatingFileHandler.java:76)
	... 22 more
java.lang.IllegalStateException: WFLYSRV0124: Could not create server data directory: /opt/data/data
	at org.jboss.as.server.ServerEnvironment.<init>(ServerEnvironment.java:473)
	at org.jboss.as.server.Main.determineEnvironment(Main.java:297)
	at org.jboss.as.server.Main.main(Main.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.modules.Module.run(Module.java:330)
	at org.jboss.modules.Main.main(Main.java:505)
```

**Comment by vnugent** [comment]
I was suggesting a possible workaround.  But yes, I concur one shouldn't have to do that.  There's a pending PR for this file permission error.
https://github.com/hawkular/hawkular-services/pull/128

**Comment by candysmurf** [comment]
@vnugent, thanks for getting back to me. Do you if this PR will fix this issue and when this PR may be merged? Can we pin to your previous docker-image for now?

**Comment by jkremser** [comment]
@candysmurf yes, the PR should fix your use case. If you don't want to wait, here is a workaround:

```bash
mkdir -p /opt/data/ && chown -R 1000:1000 /opt/data && chmod -R ug+rw /opt/data/
```

..then run the h-services container (use the `/opt/data` from host and mount it as `/opt/data` in the container, preserving the ownership and rights)

```bash
docker run --link=hawkular-cassandra -v /opt/data:/opt/data -e CASSANDRA_NODES=hawkular-cassandra -p 8080:8080 -e ADMIN_TOKEN=topsecret hawkular/hawkular-services:latest
```

> The purpose of Docker image is not to have to create a lot local stuff manually. Why do we have to do this now? Please enlighten me. Thanks for your help!

The hawkular-services container is not 100% stateless and in order to keep the state (server logs + embedded db for inventory) and not lose it during the container restarts it uses the volume from the host. Before, the command in h-services container was run as a root user so there were no rights issues, but openshift doesn't support those containers ootb so now, we run the default command as a jboss user (uid=1000). If you want to know more about this behavior, you can read https://github.com/docker/docker/issues/3124 or https://github.com/docker/docker/issues/2259

actually, other workaround should be running it as a root:

```bash
docker run --user=root --link=hawkular-cassandra -v /opt/data:/opt/data -e CASSANDRA_NODES=hawkular-cassandra -p 8080:8080 -e ADMIN_TOKEN=topsecret hawkular/hawkular-services:latest
```

**Comment by candysmurf** [comment]
@Jiri-Kremser, thanks for the alternatives. I'll try it tomorrow and let you know.

**Comment by stefannegrea** [comment]
@candysmurf, any progress with getting the new container working?

**Comment by candysmurf** [comment]
@stefannegrea, thanks for the following up. I'm going to try it today. I was busy on other works. The PR seems merged, didn't it?

**Comment by candysmurf** [comment]
@stefannegrea, I did the following command to update the repo

```
go get -u github.com/hawkular/hawkular-client-go
``` 

It didn't work for me. I still saw lots exceptions in the Docker Hawkular log.

**Comment by candysmurf** [comment]
got this error, when run the image:

````
21:40:32,324 FATAL [org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle] (metricsservice-lifecycle-thread) HAWKMETRICS200006: An error occurred trying to connect to the Cassandra cluster: java.lang.RuntimeException: org.cassalog.core.ChangeSetException: com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException: Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'
	at org.hawkular.metrics.api.jaxrs.DistributedLock.lockAndThen(DistributedLock.java:111)
	at org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle.initSchema(MetricsServiceLifecycle.java:639)
	at org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle.startMetricsService(MetricsServiceLifecycle.java:407)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.cassalog.core.ChangeSetException: com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException: Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at org.cassalog.core.CassalogImpl$_execute_closure3.doCall(CassalogImpl.groovy:137)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at groovy.lang.Closure.call(Closure.java:426)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:1946)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:1926)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:1976)
	at org.codehaus.groovy.runtime.dgm$174.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.cassalog.core.CassalogImpl.execute(CassalogImpl.groovy:109)
	at org.hawkular.metrics.schema.SchemaService.run(SchemaService.java:67)
	at org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle.lambda$initSchema$2(MetricsServiceLifecycle.java:641)
	at org.hawkular.metrics.api.jaxrs.DistributedLock.lockAndThen(DistributedLock.java:109)
	... 9 more
Caused by: com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException: Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'
	at com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException.copy(InvalidConfigurationInQueryException.java:37)
	at com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException.copy(InvalidConfigurationInQueryException.java:27)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
	at com.datastax.driver.core.Session$execute$0.call(Unknown Source)
	at org.cassalog.core.CassalogImpl.executeCQL(CassalogImpl.groovy:351)
	at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at org.cassalog.core.CassalogImpl$_applyChangeSet_closure16.doCall(CassalogImpl.groovy:323)
	at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:442)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2030)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2056)
	at org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.cassalog.core.CassalogImpl.applyChangeSet(CassalogImpl.groovy:323)
	at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at org.cassalog.core.CassalogImpl$_execute_closure3.doCall(CassalogImpl.groovy:135)
	... 28 more

```

**Comment by candysmurf** [comment]
@stefannegrea, hawkular/hawkular-services docker container is running with the above error.  When I did this command: 

```
http://192.168.99.100:8080/hawkular/metrics/status
```

The output was:

```
{"MetricsService":"FAILED","Implementation-Version":"0.26.0.Final","Built-From-Git-SHA1":"fe3ef3ccc36a0c85bcdbf3e96aae8d36a636f7f2","Cassandra":"up"}
```

I was not able to use `MetricsService`.

**Comment by candysmurf** [comment]
@vnugent, by switching to cassandra:3.0.9, it's working as expected now.

Thanks, @vnugent, @stefannegrea, @Jiri-Kremser for all your help.  Those errors reported were for cassandra:3.7. 

Last not the lease, may I know when you have changes like new ADMIN_TOKEN env, how will I get such update? Our product depends on your images. Thank you.
